// The ComfyUI custom node TurboLLM installs (in-app) to coordinate the GPU. It is
// PUSH, not poll: it hooks ComfyUI's PromptQueue in-process and tells TurboLLM the
// instant a render starts / the queue drains. We ship it as a generated string (with
// TurboLLM's own URL baked in) rather than a .py file so it travels inside the npm
// package and is written into the user's chosen custom_nodes dir at install time.
//
// Contract with the daemon (see chat ../engines/comfy-guard.ts):
//   • rising edge (idle → first job enqueued): blocking POST {base}/api/v1/comfyui/acquire
//     BEFORE the job is enqueued, so TurboLLM frees VRAM before ComfyUI executes.
//   • queue drained (last task_done): POST {base}/api/v1/comfyui/release → reload.

/** Version stamp written into the node so the installer can detect/upgrade it. */
export const GATE_VERSION = 2

/** Render the Python source for the gate node, with TurboLLM's base URL baked in.
 *  `baseUrl` is TurboLLM's own origin (e.g. http://127.0.0.1:6996), reachable from
 *  the ComfyUI process (same machine → loopback, so no API key is needed). */
export function gateNodeSource(baseUrl: string): string {
  const base = baseUrl.replace(/\/+$/, '')
  // Embed as a JSON string literal so any quotes/backslashes are escaped for Python
  // (JSON string syntax is a subset of Python's, so this is safe to paste verbatim).
  const baseLit = JSON.stringify(base)
  return `# Auto-generated by TurboLLM — ComfyUI GPU gate (push, no polling). v${GATE_VERSION}
# Installed via TurboLLM Settings -> ComfyUI. Safe to delete this folder to uninstall.
#
# Hooks ComfyUI's PromptQueue in-process and notifies TurboLLM so it can unload its
# model before a render starts and reload it when the queue drains. Edit TURBOLLM_URL
# below if you move TurboLLM to a different port.
from __future__ import annotations

import json
import threading
import urllib.error
import urllib.request

# ComfyUI custom-node contract: empty mappings = we contribute no graph nodes.
NODE_CLASS_MAPPINGS: dict = {}
NODE_DISPLAY_NAME_MAPPINGS: dict = {}

TURBOLLM_URL = ${baseLit}
GATE_VERSION = ${GATE_VERSION}
ACQUIRE_TIMEOUT_SEC = 60.0  # max wait for TurboLLM to free VRAM before we proceed
RELEASE_TIMEOUT_SEC = 10.0
LOG_PREFIX = "[turbollm_gate]"

_lock = threading.Lock()
_busy = False  # True between the rising edge and the queue draining


def _log(msg: str) -> None:
    print(f"{LOG_PREFIX} {msg}", flush=True)


def _post(path: str, timeout: float) -> bool:
    url = TURBOLLM_URL.rstrip("/") + path
    req = urllib.request.Request(url, data=b"{}", method="POST",
                                 headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            resp.read()
        return True
    except (urllib.error.URLError, TimeoutError, ConnectionError, OSError) as e:
        # TurboLLM not running / unreachable: nothing to coordinate — let ComfyUI run.
        _log(f"POST {path} failed ({e}); proceeding without TurboLLM.")
        return False
    except Exception as e:  # noqa: BLE001 — never let coordination crash a render
        _log(f"POST {path} error: {e}; proceeding.")
        return False


def _acquire_blocking() -> None:
    """Free TurboLLM's VRAM and BLOCK its loads. Blocks until TurboLLM confirms."""
    _post("/api/v1/comfyui/acquire", ACQUIRE_TIMEOUT_SEC)


def _free_self() -> None:
    """Unload ComfyUI's own models and clear the CUDA cache so VRAM is available
    for TurboLLM to reload its model. Called on the release edge (queue drained),
    before notifying TurboLLM. In-process — no HTTP roundtrip."""
    try:
        import comfy.model_management as mm  # type: ignore[import]
        mm.unload_all_models()
        mm.soft_empty_cache()
        _log("freed ComfyUI model cache.")
    except Exception as e:  # noqa: BLE001
        _log(f"could not free ComfyUI models ({e}); continuing.")


def _release() -> None:
    _post("/api/v1/comfyui/release", RELEASE_TIMEOUT_SEC)


def _install_hooks() -> None:
    """Wrap PromptQueue.put / task_done so we fire on the exact edges. Patches the
    CLASS (the queue instance is created after custom nodes import), so every instance
    picks up the hooks."""
    try:
        import execution  # ComfyUI core module
    except Exception as e:  # noqa: BLE001
        _log(f"could not import ComfyUI 'execution' module: {e}; gate inactive.")
        return

    PromptQueue = getattr(execution, "PromptQueue", None)
    if PromptQueue is None or getattr(PromptQueue, "_turbollm_gated", False):
        return

    orig_put = PromptQueue.put
    orig_task_done = PromptQueue.task_done

    def put(self, item, *args, **kwargs):
        global _busy
        # Acquire BEFORE enqueuing so the worker can't start executing until TurboLLM
        # has freed the GPU. Only on the rising edge (idle -> busy).
        with _lock:
            if not _busy:
                _busy = True
                acquire = True
            else:
                acquire = False
        if acquire:
            _acquire_blocking()
        return orig_put(self, item, *args, **kwargs)

    def task_done(self, *args, **kwargs):
        global _busy
        result = orig_task_done(self, *args, **kwargs)
        try:
            remaining = self.get_tasks_remaining()
        except Exception:  # noqa: BLE001
            remaining = 0
        if remaining <= 0:
            do_release = False
            with _lock:
                if _busy:
                    _busy = False
                    do_release = True
            if do_release:
                _free_self()
                _release()
        return result

    PromptQueue.put = put
    PromptQueue.task_done = task_done
    PromptQueue._turbollm_gated = True
    _log(f"hooks installed (v{GATE_VERSION}); TurboLLM at {TURBOLLM_URL}")


_install_hooks()

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
`
}
