"""Shared slash-command metadata for help and completion."""

from collections import OrderedDict


COMMAND_TREE: dict[str, list[str]] = OrderedDict(
    [
        ("status", []),
        ("health", []),
        ("doctor", []),
        ("start", []),
        ("stop", []),
        ("search", []),
        ("dashboard", []),
        ("files", ["list", "upload", "download", "delete", "mkdir"]),
        ("projects", ["list", "create", "info", "delete"]),
        ("rules", ["list", "create", "delete", "export", "import"]),
        ("agents", ["list", "info", "run", "update"]),
        ("generate", ["csv", "image"]),
        ("jobs", ["list", "status", "watch", "cancel"]),
        ("settings", ["list", "get", "set"]),
        ("models", ["list", "active", "set"]),
        ("index", ["document", "status", "entity", "all"]),
        ("backup", ["create", "list", "download", "restore", "delete"]),
        ("family", ["list", "status", "sync", "health"]),
        ("logs", ["tail", "search", "stats"]),
        ("rag", ["status", "query", "entities", "eval"]),
        ("clients", ["list", "create", "info", "delete"]),
        ("websites", ["list", "create", "info", "scrape", "delete"]),
        ("tasks", ["list", "create", "info", "start", "download", "delete"]),
        ("images", ["list", "generate", "status", "models", "delete"]),
        (
            "videos",
            ["list", "generate", "from-image", "status", "models", "delete", "download", "combine"],
        ),
        ("remember", []),
        ("memory", ["list", "search", "delete", "clear"]),
        ("new", []),
        ("clear", []),
        ("history", []),
        ("export", []),
        ("config", ["server", "theme", "timeout", "api_key"]),
        ("theme", []),
        ("quality", ["scorecard"]),
        ("help", []),
        ("quit", []),
        ("exit", []),
    ]
)


COMMAND_META: dict[str, str] = {
    "status": "System status overview",
    "health": "Service health checks",
    "doctor": "Diagnose common issues",
    "start": "Start Guaardvark services",
    "stop": "Stop Guaardvark services",
    "search": "Search across content",
    "dashboard": "System dashboard",
    "files": "File management",
    "projects": "Project management",
    "rules": "System prompt rules",
    "agents": "Agent management",
    "generate": "Generate content",
    "jobs": "Background job control",
    "settings": "View/change settings",
    "models": "LLM model management",
    "index": "RAG indexing operations",
    "backup": "Backup & restore",
    "family": "Multi-instance family",
    "logs": "Log viewing & search",
    "rag": "RAG pipeline tools",
    "clients": "Client management",
    "websites": "Website management",
    "tasks": "Task management",
    "images": "Image generation",
    "videos": "Video generation",
    "remember": "Save to memory",
    "memory": "Manage saved memories",
    "new": "New conversation",
    "clear": "Clear screen",
    "history": "Command history",
    "export": "Export conversation",
    "config": "REPL configuration",
    "theme": "Switch colour theme",
    "quality": "Quality scorecard and gates",
    "help": "Show help",
    "quit": "Exit the REPL",
    "exit": "Exit the REPL",
}
